<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/10 21:17:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf14',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
